version: '3.8'

services:

  cccat12-database:
    image: postgres:alpine
    container_name: cccat12-postgres-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/db.sql

  pg-admin:
    image: dpage/pgadmin4
    depends_on:
      - cccat12-database
    container_name: pg-database-admin
    ports:
      - "8081:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
